### ISSUE TITLE
The terrain.npy file is missing in your Deep-RL-Collision-Avoidance-TTK4550-Fordypningsoppgave project.

### ISSUE THREAD

**Issue by 9527dogdog** [halvorot/power-asset-optimizer#5]
Sir, hello. The terrain.py file you provided (https://1drv.ms/u/s!AuskcXXxkWxWh6pG0EDdXqPNUbJ_KA?e=uAuZO4) has expired and cannot be found. Could you please resend it?Can I get the file from elsewhere? Thank you very much for your help.

**Comment by halvorot** [comment]
Closing the issue because it is not related to this repository.
